quarkus:
  datasource:
    db-kind: h2
    username: sa
    password:
    jdbc:
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MySQL

  hibernate-orm:
    log:
      sql: true
    schema-management:
      strategy: drop-and-create